make:
	gcc -o wshell wshell.c -Wall -Werror
		gcc -o test test.c -Wall -Werror
		gcc -o copy copy.c -Wall -Werror

copy:
	gcc -o copy copy.c -Wall -Werror

try:
	rm -f test
	gcc -o test test.c -Wall -Werror
	./test
